# This is a basic workflow to help you get started with Actions

name: run script

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7 #install the python needed
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip pandas
        run: python -m pip install --upgrade pip os
      - name: execute py script # run the run.py to get the latest data
        run: |
          python AIMLSummary_convert_table.py output/out.csv
      - name: Commit and Push
        run: |
          git config --global user.name "KSJangam"
          git config --global user.email "kjangam8@gmail.com"
          git add -A
          git commit -m "output file created"
          git push
    # Steps represent a sequence of tasks that will be executed as part of the job
  